db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "123"
  dbname: "test_avito"
server:
  insecurePort: ":9000"
  securePort: ":9001"
  username: "user"
  password: "$2a$10$u1IbORaP8UDbmhf2Vt9XJO22Ow52FlDyFF3Joh4d9ic35rpTLbmRq"